### ISSUE TITLE
use postman to post signup, please advise it

### ISSUE THREAD

**Issue by zachary** [bezkoder/node-js-jwt-auth#2]
Unhandled rejection Error: WHERE parameter "username" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:13)
    at /Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (/Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (/Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
    at QueryInterface.select (/Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/query-interface.js:1122:27)
    at /Users/zach/dev/js/node-js-jwt-auth/node_modules/sequelize/lib/model.js:1757:34
    at tryCatcher (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/zach/dev/js/node-js-jwt-auth/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by zachary** [comment]
change postman body from text to json to resolve it.thanks

**Comment by dylanrychlik** [comment]
This doesnt fix issue for me
